-- ============================================================
-- MIGRACIÓN: Historial de Rifas
-- Ejecutar en Supabase → SQL Editor
-- ============================================================

-- 1. Tabla de aportes de capital por rifa
CREATE TABLE IF NOT EXISTS capital_rifas (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  rifa smallint NOT NULL,
  inversionista text NOT NULL,
  concepto text NOT NULL,
  valor bigint NOT NULL,
  requiere_recapitalizacion boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- 2. Tabla de gastos operacionales históricos (Rifas 1-3)
CREATE TABLE IF NOT EXISTS gastos_historicos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  rifa smallint NOT NULL,
  quien_pago text NOT NULL,
  descripcion text NOT NULL,
  valor bigint NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- ============================================================
-- DATOS: Capital aportado por rifa
-- ============================================================
INSERT INTO capital_rifas (rifa, inversionista, concepto, valor, requiere_recapitalizacion) VALUES
-- ===== RIFA 1 =====
(1, 'Papá',     'Impuestos (1era rifa)',  7300000,   true),
(1, 'Papá',     'XTZ (1era rifa)',        14200000,  true),
(1, 'Papá',     'N-Max (1era rifa)',      22000000,  true),
(1, 'Mateo',    'Camioneta (1era rifa)',  105000000, true),
(1, 'Papá',     'CDT (1era rifa)',        30000000,  false),

-- ===== RIFA 2 =====
(2, 'Mateo',    'Compra de camioneta LPN',    62500000, true),
(2, 'Alejandro','Compra de camioneta LPN',    22000000, true),
(2, 'Papá',     'Compra de camioneta LPN',    49000000, true),
(2, 'Alejandro','Restante N Max',             21500000, true),
(2, 'Alejandro','CDT (2da rifa)',              5000000, false),
(2, 'Mateo',    'CDT (2da rifa)',              5000000, false),
(2, 'Papá',     'CDT (1era rifa) continuado', 30000000, false),

-- ===== RIFA 3 =====
(3, 'Mateo',    'Compra camioneta estacas',   69911000, true),
(3, 'Alejandro','Compra camioneta estacas',   67600000, true),
(3, 'Mateo',    'MT 15',                      16271000, true),
(3, 'Mateo',    'N Max',                      12600000, true),
(3, 'Alejandro','N Max',                       9200000, true),
(3, 'Mateo',    'CDT',                        60000000, false),

-- ===== RIFA 4 =====
(4, 'Papá',     'Apartamento',               320000000, true);

-- ============================================================
-- DATOS: Gastos operacionales históricos Rifa 1
-- ============================================================
INSERT INTO gastos_historicos (rifa, quien_pago, descripcion, valor) VALUES
(1, 'Mateo',    'Mano de obra Beto',                       60000),
(1, 'Mateo',    'Madera Sebastian',                        877000),
(1, 'Mateo',    'Anticipo Jhonatan publicidad',            500000),
(1, 'Mateo',    'Mano de obra Care vieja',                 500000),
(1, 'Mateo',    'Mano de obra Pipe y Oscar',               300000),
(1, 'Mateo',    'Ventiladores y bases',                    510000),
(1, 'Mateo',    'Mano de obra Pipe y Oscar',               120000),
(1, 'Mateo',    'Boleteria',                               490000),
(1, 'Mateo',    'Mano de obra beto lampara de lujo',        20000),
(1, 'Mateo',    'Pipe madera teclados',                    250000),
(1, 'Mateo',    'Lampara con riel',                         90000),
(1, 'Mateo',    'Mano de obra lampara con riel',           120000),
(1, 'Mateo',    'Tapete',                                  230000),
(1, 'Mateo',    'Ventilador de barra',                     220000),
(1, 'Mateo',    'Mano de obra avisos luminosos de afuera', 100000),
(1, 'Mateo',    'Mano de obra Henry bomba',                100000),
(1, 'Mateo',    'Mano de obra Javier',                     400000),
(1, 'Mateo',    'Camioneta pintada estacas',               500000),
(1, 'Mateo',    'Scanner Henry',                            50000),
(1, 'Mateo',    'Filtro',                                   28000),
(1, 'Mateo',    'Julian pereira',                         2770000),
(1, 'Mateo',    'Multilujos',                              700000),
(1, 'Mateo',    'Gasolina diesel',                         100000),
(1, 'Mateo',    'Multilujos',                              500000),
(1, 'Mateo',    'Ferreteria',                               98900),
(1, 'Mateo',    'Ferreteria Lampara',                      196000),
(1, 'Mateo',    'Ferreteria la llave',                      36800),
(1, 'Mateo',    'Ferreteria la llave',                      38000),
(1, 'Mateo',    'Ferreteria',                               26400),
(1, 'Mateo',    'Proquimel',                               118000),
(1, 'Mateo',    'Ferreteria',                              175000),
(1, 'Mateo',    'Vidrieria',                               200000),
(1, 'Mateo',    'Filtros y aceites',                        30000),
(1, 'Mateo',    'Andamios',                                 24000),
(1, 'Mateo',    'Electricos',                               52900),
(1, 'Mateo',    'Ferreteria',                               17600),
(1, 'Mateo',    'Cintas led',                               98000),
(1, 'Mateo',    'El hogar',                                191000),
(1, 'Mateo',    'Ferreteria',                              141000),
(1, 'Mateo',    'El hogar',                                 47000),
(1, 'Mateo',    'Aglomerados',                              40800),
(1, 'Mateo',    'Televisores',                            2300000),
(1, 'Mateo',    'Bomberos',                                100000),
(1, 'Mateo',    'Deuda rifa (descuento)',                -1380000),
(1, 'Mateo',    'Impuestos y traspaso',                    870000),
(1, 'Mateo',    'Peritaje',                                270000),
(1, 'Mateo',    'Viaticos',                                300000),
(1, 'Mateo',    'Multilujos',                            2000000),
(1, 'Mateo',    'Peritaje segunda camioneta',              180000),
(1, 'Mateo',    'Gasolina y peajes',                       280000),
(1, 'Mateo',    'Peritaje',                                260000),
(1, 'Mateo',    'Camioneta',                                50000),
(1, 'Mateo',    'Viaticos',                                300000),
(1, 'Mateo',    'Botiquin Don Ambrioso',                   230000),
(1, 'Mateo',    'Kit de herramienta',                       68000),
(1, 'Mateo',    'Biaticos papá',                           100000),
(1, 'Mateo',    'Slingas',                                 209000),
(1, 'Mateo',    'Gasolina y peajes',                       150000),
(1, 'Mateo',    'Lavadas',                                  60000),
(1, 'Mateo',    'Moño para grabar',                         50000),
(1, 'Mateo',    'Omar contador creación de la SAS',        500000),
(1, 'Mateo',    'Grua',                                    180000),
(1, 'Mateo',    'Gasolina y peajes',                        65000),
(1, 'Mateo',    'Arreglo camioneta Pereira',               716000),
(1, 'Mateo',    'Teclados y bases',                        300000),
(1, 'Mateo',    'Descargue',                               150000),
(1, 'Mateo',    'Publicidad',                             1700000),
(1, 'Mateo',    'Tecnomecanica',                           307000),
(1, 'Mateo',    'Quimiaseo',                                72200),
(1, 'Mateo',    'Homecenter',                              500000),
(1, 'Mateo',    'Cambio de guardas',                       140000),
(1, 'Mateo',    'Maderas y canaletas',                      70000),
(1, 'Mateo',    'Arriendo oct',                          1200000),
(1, 'Mateo',    'Arriendo nov',                          1200000),
(1, 'Mateo',    'Camara y comercio',                       302000),
(1, 'Mateo',    'Renta',                                   175000),
(1, 'Mateo',    'Internet',                                 52000),
(1, 'Mateo',    'Internet',                                131000),
(1, 'Mateo',    'Almuerzo',                                342000),
(1, 'Mateo',    'Publicidad oficina',                      940000),
(1, 'Mateo',    'Premio del sábado (Alexandra Bastidas)', 1000000),
(1, 'Mateo',    'Arriendo sep',                            520000),
(1, 'Mateo',    'Depósito del local',                      600000),
(1, 'Mateo',    'Ganancia venta 1era camioneta (descuento)', -10000000),
(1, 'Mateo',    'Llantas y rines',                       5000000),
(1, 'Mateo',    'Compra camioneta (excedente 105M)',      3000000),
(1, 'Mateo',    'Mensualidad contador',                    500000),
(1, 'Alejandro','Microfonos',                              200000),
(1, 'Alejandro','Premio del sábado',                     1000000),
(1, 'Alejandro','Cambio de color',                         710000),
(1, 'Alejandro','Tecnomecanica',                           307000),
(1, 'Alejandro','Pago premio (Carlos Alvarez)',           1000000),
(1, 'Alejandro','Tela para el carro',                      300000),
(1, 'Alejandro','Moños y bombas',                          145000),
(1, 'Alejandro','Viaticos Ibague',                         400000),
(1, 'Alejandro','Premio en vivo',                        3000000),

-- ============================================================
-- DATOS: Gastos operacionales históricos Rifa 2
-- ============================================================
(2, 'Alejandro','Tratamiento rav',                        2500000),
(2, 'Mateo',    'Tratamiento rav',                        2500000),
(2, 'Alejandro','EDSA',                                   2000000),
(2, 'Mateo',    'Intereses Fernando',                     3000000),
(2, 'Mateo',    'Eslingas',                                200000),
(2, 'Mateo',    'Multilujos Manizales',                    900000),
(2, 'Alejandro','Gastos multilujos',                       890000),
(2, 'Alejandro','Cables bateria',                           88500),
(2, 'Alejandro','Biaticos Zarzal',                        1250000),
(2, 'Mateo',    'Viaticos Zarzal',                         150000),
(2, 'Mateo',    'Lavada camioneta',                         73000),
(2, 'Mateo',    'Internet oficina',                         87000),
(2, 'Mateo',    'Servicios publicos',                      220000),
(2, 'Mateo',    'Pagos impuestos La Perla',               2320000),
(2, 'Alejandro','Pagos impuestos La Perla',               4880000),
(2, 'Mateo',    'Pago premio sábado 06 dic',              1000000),
(2, 'Alejandro','Contrato de confidencialidad',            150000),
(2, 'Alejandro','Pago arrendamiento Los Plata',           1200000),
(2, 'Alejandro','Aire acondicionado',                     1449000),
(2, 'Alejandro','Servicio aire acondicionado',             924000),
(2, 'Alejandro','Pago premio 10 dic',                    1000000),
(2, 'Mateo',    'Servicios publicos',                      491000),
(2, 'Mateo',    'Mensualidad contador',                   1250000),
(2, 'Mateo',    'Mensualidad padel',                      1080000),
(2, 'Mateo',    'Pago internet oficina',                    74900),
(2, 'Alejandro','Grua camioneta Zarzal',                   550000),
(2, 'Mateo',    'Intereses Fernando',                     3000000),
(2, 'Alejandro','Respuesta col juegos',                    200000),
(2, 'Alejandro','Pago premio 3 millones 25 dic',          3000000),
(2, 'Alejandro','Gasto premio regalo',                    3000000),
(2, 'Alejandro','Exploradoras',                            140000),
(2, 'Alejandro','Improntas',                               250000),
(2, 'Alejandro','Video en vivo',                           250000),
(2, 'Mateo',    'Contador',                                250000),

-- ============================================================
-- DATOS: Gastos operacionales históricos Rifa 3
-- ============================================================
(3, 'Mateo',    'Peritaje',                                348300),
(3, 'Mateo',    'Llantas',                                3000000),
(3, 'Mateo',    'Tratamiento nanoceramico',                750000),
(3, 'Mateo',    'Bomper delantero y pechera',              500000),
(3, 'Mateo',    'Jhonatan publicidad',                     300000),
(3, 'Alejandro','Impuestos estacas',                      9000000),
(3, 'Mateo',    'Aire',                                    250000),
(3, 'Mateo',    'Internet',                                 75000),
(3, 'Mateo',    'Arrendamiento oficina',                  1200000),
(3, 'Mateo',    'Arreglo camioneta LPN',                   600000),
(3, 'Mateo',    'Asesoria Jair',                           525000),
(3, 'Mateo',    'Mensualidad contador',                    250000),
(3, 'Mateo',    'Servicios publicos',                      292000),
(3, 'Mateo',    'Parqueadero LPN',                         120000),
(3, 'Mateo',    'Creación de marca',                       700000),
(3, 'Mateo',    'Tanqueo camioneta estacas',               131000),
(3, 'Mateo',    'Peaje',                                    17800),
(3, 'Mateo',    'Desayuno',                                177000),
(3, 'Mateo',    'Arreglo carro y peajes',                  200000),
(3, 'Mateo',    'Comida',                                  595000),
(3, 'Mateo',    'Master IA',                             8000000),
(3, 'Alejandro','Pago premio 1er adicional',             10000000),
(3, 'Alejandro','Arreglo camioneta James',                1048000),
(3, 'Alejandro','Conversor para live',                     550000),
(3, 'Alejandro','Pago premios',                           3000000),
(3, 'Alejandro','Gasto alquiler camara',                   100000),
(3, 'Alejandro','Juegos pirotecnicos',                     174000),
(3, 'Alejandro','Camioneta papá',                          140000),
(3, 'Alejandro','Video y edicion de videos',               650000),
(3, 'Alejandro','Tanqueo carros',                          255000),
(3, 'Alejandro','Viaticos James',                          150000),
(3, 'Alejandro','Restante arreglo camioneta James',       1120027);
